### ISSUE TITLE
Authentication adapter "verifyAction" was not found.

### ISSUE THREAD

**Issue by AlphabyteSoft** [andrej-griniuk/cakephp-two-factor-auth#10]
Hello!

I think I reached end of Internet looking over this error.
I installed fresh cakephp 3.4.5 on my server.
Installed your plugin.
Added database field, plugin loader in bootstrap.php, changed AppController.php.

I got this annoying error and I don't know what to do. Can you give me a hint on how to resolve this?

Thanks!

**Comment by andrej-griniuk** [comment]
Hi @AlphabyteSoft 
sorry for confusion, it was a mistake in README. `verifyAction` should go into `TwoFactorAuth.Form` in component config. Fixed now.

**Comment by AlphabyteSoft** [comment]
Omg, I tried all the ways, never thought about adding into `TwoFactorAuth.Form`.
Thanks @andrej-griniuk!
