### ISSUE TITLE
Verification code invalid

### ISSUE THREAD

**Issue by ElRochito** [andrej-griniuk/cakephp-two-factor-auth#11]
I try this code.
But when I scan QRcode in Authy or Google Authentificator, the code isn't equals to my code print.
`$secret        = "UBSZYUT3FBIGGDZR";
        $code          = $this->Auth->tfa->getCode($secret);
        echo "<img src='".$this->Auth->tfa->getQRCodeImageAsDataUri("Bahamas", $secret)."'/>";
        echo $code . "<br/>";
        echo $this->Auth->tfa->verifyCode($secret, "346259", 0) ? "OK" : "NOK<br/>";
        echo $this->Auth->tfa->verifyCode($secret, $code, 0) ? "OK" : "NOK";`

**Comment by andrej-griniuk** [comment]
Am I understanding correctly that you replace "346259" with an actual the code from Authy? If so, everything works for me with your example - show OK OK with actual code.

I hope you're not trying it with same "346259" code all the time, cause it's only valid for short period of time.
