### ISSUE TITLE
verifyCode() is not available in the component

### ISSUE THREAD

**Issue by koraykupe** [andrej-griniuk/cakephp-two-factor-auth#17]
Hi,
I need to use `verifyCode()` method in a controller, but there is no such a method in the component. It does exist on `TwoFactorAuth` class. Why is that? How should do I verify the code?

I already loaded the component, so didn't want to create an object from `TwoFactorAuth`.

**Comment by andrej-griniuk** [comment]
hi @koraykupe 
There actually is `verifyCode()` method on the component as you can see here: https://github.com/andrej-griniuk/cakephp-two-factor-auth/blob/master/src/Controller/Component/TwoFactorAuthComponent.php#L28
Also there is `getTfa()` method which returns a `TwoFactorAuth` object instance. Hope this helps
