### ISSUE TITLE
CakePHP 5 plugin class name

### ISSUE THREAD

**Issue by dereuromark** [andrej-griniuk/cakephp-two-factor-auth#23]
https://github.com/andrej-griniuk/cakephp-two-factor-auth/blob/master/src/Plugin.php

This is not a valid class name for 5.x
See docs

Should be YourPluginNamePlugin class

**Comment by dereuromark** [comment]
PS: I merged https://github.com/FriendsOfCake/awesome-cakephp/pull/445 already

**Comment by andrej-griniuk** [comment]
Thank you, fixed!
