### ISSUE TITLE
Release 3.0 not having isEnabled2faProperty

### ISSUE THREAD

**Issue by zegert** [andrej-griniuk/cakephp-two-factor-auth#24]
I'm currently working on a project that uses CakePHP 4.3 and uses this plugin. We are dependant on the `isEnabled2faProperty` and version 3.0 doesn't have that one yet. 

Update Release 3.0 to [this commit](https://github.com/andrej-griniuk/cakephp-two-factor-auth/commit/aff450b66a64aeac5bf01d5c9e5b53e109eedafd) so that's included in the 3.0 release as well.

Commit: aff450b66a64aeac5bf01d5c9e5b53e109eedafd as base of the 3.0 release.

PR that adds this feature: https://github.com/andrej-griniuk/cakephp-two-factor-auth/pull/18

If i need to create anything let me please know.

Thanks in advance.

**Comment by andrej-griniuk** [comment]
Hi @zegert 
thanks for bringing this up. Created a [3.1.0](https://github.com/andrej-griniuk/cakephp-two-factor-auth/releases/tag/3.1.0) release based on that commit.

**Comment by zegert** [comment]
Hi @andrej-griniuk,

Thanks for inplementing this.

-Zegert
