### ISSUE TITLE
isEnabled2faProperty check is not backwards compatible with custom field for secret

### ISSUE THREAD

**Issue by alexvanniel** [andrej-griniuk/cakephp-two-factor-auth#25]
In the comments for the commit regarding the isEnabled2faProperty change, it says that the check for this property is done in a backwards compatible way.
However, when I updated to 3.1.0 and tested the login procedure, I was not asked for my TFA code during login and the entire TFA procedure was bypassed.
This made no sense to me, until I figured that we have implemented a custom secretProperty which is different from the default property and thus also differs from the isEnabled2faProperty value set as default.
Because this property was not set (to the custom property) the check to see if the TFA is enabled, is unable to fetch the default `secret` field from the database since we don't have this field declared in our database.
This somehow enabled the user to bypass the TFA procedure entirely.
Obviously, after configuring the isEnabled2faProperty to our custom field in the database, the TFA check worked as expected again.
I would argue that in order for this to be backwards compatible, the ddefault value for the isEnabled2faProperty should default to the value of the property secretProperty. Or is there something I am missing / not understanding?

**Comment by andrej-griniuk** [comment]
Hi @alexvanniel 
Sorry for the delay.
You're right, if `secretProperty` is not `secret`, then `isEnabled2faProperty` breaks the BC. Completely overlooked that. Fixed now and re-released v.3.1.0. Sorry for the inconvenience caused.
