### ISSUE TITLE
Controller initialization

### ISSUE THREAD

**Issue by bradycharron-sephone** [andrej-griniuk/cakephp-two-factor-auth#3]
After the secret value has been saved to the database, and the user tries to login again, there is the following error:
> Fatal error: Call to a member function allow() on boolean in /vendor/andrej-griniuk/cakephp-two-factor-auth/src/Controller/TwoFactorAuthController.php on line 24

This seems to be due to the inaccessibility to the Auth Component in the TwoFactorAuth Controller.  I was able to get a work around for this by implementing the following code in the TwoFactorAuth Controller:
````
public function initialize()
{
	parent::initialize();
	$this->loadComponent('Auth');
}
````

**Comment by jorisvaesen** [comment]
Why not let TwoFactorAuthController extend AppController in stead of Controller?

**Comment by bradycharron-sephone** [comment]
That sounds like it should work, but it doesn't

**Comment by andrej-griniuk** [comment]
Can't reproduce. Closing.
