### ISSUE TITLE
When I generate the code?

### ISSUE THREAD

**Issue by lira92** [andrej-griniuk/cakephp-two-factor-auth#4]
Hi guys i want to generate the code ($this->Auth->tfa->getCode()) after the username and password has validated, and send a email with this code, where i put my logic?

**Comment by jorisvaesen** [comment]
It depends on from where you are sending the mail. 

The code should be generated from the controller since that's the place when `$this->Auth` is available. From there you can pass the code to where you sent the mail.

**Comment by andrej-griniuk** [comment]
Thanks @jorisvaesen
