### ISSUE TITLE
Response Object Location method deprecated in 3.4.x

### ISSUE THREAD

**Issue by anupkale** [andrej-griniuk/cakephp-two-factor-auth#6]
In the FormAuthneticate.php you are using `$response->location($verifyAction);`. The location is now deprecated and does not send over the Flash messages in the redirect.

Are you planning to update the framework according to the newer methods.

I tried to update my implementation of this plugin and it failed miserably.

**Comment by andrej-griniuk** [comment]
Hi @anupkale,

thanks for pointing this out, will try to dedicate some time this week to fix it.

**Comment by anupkale** [comment]
@andrej-griniuk Thank you. Looking forward to the changes. 
Hopefully, I will get to learn from the update.

**Comment by andrej-griniuk** [comment]
v1.1. release tagged with CakePHP 3.4 support.
